// Generated by .NET Reflector from C:\Projects\Skylines\DifficultyMod\DifficultyMod\libs\Assembly-CSharp.dll
using ColossalFramework;
using ColossalFramework.Globalization;
using ColossalFramework.Math;
using System;
using System.Runtime.InteropServices;
using UnityEngine;

public class FireTruckAIMod : CarAIMod
{
    public int m_fireFightingRate = 30;
    public int m_firemanCount = 2;
    public int m_hoseCount = 1;

    public override bool ArriveAtDestination(ushort vehicleID, ref Vehicle vehicleData)
    {
        if ((vehicleData.m_flags & Vehicle.Flags.WaitingTarget) != Vehicle.Flags.None)
        {
            return false;
        }
        if ((vehicleData.m_flags & Vehicle.Flags.GoingBack) != Vehicle.Flags.None)
        {
            return this.ArriveAtSource(vehicleID, ref vehicleData);
        }
        return this.ArriveAtTarget(vehicleID, ref vehicleData);
    }

    private bool ArriveAtSource(ushort vehicleID, ref Vehicle data)
    {
        if (data.m_sourceBuilding == 0)
        {
            Singleton<VehicleManager>.instance.ReleaseVehicle(vehicleID);
            return true;
        }
        this.RemoveSource(vehicleID, ref data);
        Singleton<VehicleManager>.instance.ReleaseVehicle(vehicleID);
        return true;
    }

    private bool ArriveAtTarget(ushort vehicleID, ref Vehicle data)
    {
        if (data.m_targetBuilding == 0)
        {
            Singleton<VehicleManager>.instance.ReleaseVehicle(vehicleID);
            return true;
        }
        for (int i = 0; i < this.m_firemanCount; i++)
        {
            if (i < this.m_hoseCount)
            {
                this.CreateFireman(vehicleID, ref data, Citizen.AgePhase.Adult1);
            }
            else
            {
                this.CreateFireman(vehicleID, ref data, Citizen.AgePhase.Adult0);
            }
        }
        data.m_flags |= Vehicle.Flags.Stopped;
        return false;
    }

    public override void BuildingRelocated(ushort vehicleID, ref Vehicle data, ushort building)
    {
        base.BuildingRelocated(vehicleID, ref data, building);
        if (building == data.m_sourceBuilding)
        {
            if ((data.m_flags & Vehicle.Flags.GoingBack) != Vehicle.Flags.None)
            {
                this.InvalidPath(vehicleID, ref data, vehicleID, ref data);
            }
        }
        else if ((building == data.m_targetBuilding) && ((data.m_flags & Vehicle.Flags.GoingBack) == Vehicle.Flags.None))
        {
            this.InvalidPath(vehicleID, ref data, vehicleID, ref data);
        }
    }

    protected override float CalculateTargetSpeed(ushort vehicleID, ref Vehicle data, float speedLimit, float curve)
    {
        if ((data.m_flags & Vehicle.Flags.Emergency2) == Vehicle.Flags.None)
        {
            return base.CalculateTargetSpeed(vehicleID, ref data, speedLimit, curve);
        }
        return Mathf.Min(base.CalculateTargetSpeed(vehicleID, ref data, speedLimit * 1.25f, curve * 0.5f), base.m_info.m_maxSpeed);
    }

    public override bool CanLeave(ushort vehicleID, ref Vehicle vehicleData)
    {
        CitizenManager instance = Singleton<CitizenManager>.instance;
        bool flag = true;
        uint citizenUnits = vehicleData.m_citizenUnits;
        int num2 = 0;
        while (citizenUnits != 0)
        {
            uint nextUnit = instance.m_units.m_buffer[citizenUnits].m_nextUnit;
            for (int i = 0; i < 5; i++)
            {
                uint citizen = instance.m_units.m_buffer[citizenUnits].GetCitizen(i);
                if (citizen != 0)
                {
                    ushort index = instance.m_citizens.m_buffer[citizen].m_instance;
                    if (index != 0)
                    {
                        CitizenInfo info = instance.m_instances.m_buffer[index].Info;
                        if (info.m_class.m_service == base.m_info.m_class.m_service)
                        {
                            if ((instance.m_instances.m_buffer[index].m_flags & CitizenInstance.Flags.EnteringVehicle) == CitizenInstance.Flags.None)
                            {
                                info.m_citizenAI.SetTarget(index, ref instance.m_instances.m_buffer[index], 0);
                            }
                            flag = false;
                        }
                    }
                }
            }
            citizenUnits = nextUnit;
            if (++num2 > 0x80000)
            {
                CODebugBase<LogChannel>.Error(LogChannel.Core, "Invalid list detected!\n" + System.Environment.StackTrace);
                return flag;
            }
        }
        return flag;
    }

    private void CreateFireman(ushort vehicleID, ref Vehicle data, Citizen.AgePhase agePhase)
    {
        SimulationManager instance = Singleton<SimulationManager>.instance;
        CitizenManager manager2 = Singleton<CitizenManager>.instance;
        CitizenInfo info = manager2.GetGroupCitizenInfo(ref instance.m_randomizer, base.m_info.m_class.m_service, Citizen.Gender.Male, agePhase);
        if (info != null)
        {
            int family = instance.m_randomizer.Int32(0x100);
            uint citizen = 0;
            if (manager2.CreateCitizen(out citizen, 90, family, ref instance.m_randomizer, info.m_gender))
            {
                ushort num3;
                if (manager2.CreateCitizenInstance(out num3, ref instance.m_randomizer, info, citizen))
                {
                    Vector3 randomDoorPosition = data.GetRandomDoorPosition(ref instance.m_randomizer, VehicleInfo.DoorType.Exit);
                    info.m_citizenAI.SetCurrentVehicle(num3, ref manager2.m_instances.m_buffer[num3], 0, 0, randomDoorPosition);
                    info.m_citizenAI.SetTarget(num3, ref manager2.m_instances.m_buffer[num3], data.m_targetBuilding);
                    manager2.m_citizens.m_buffer[citizen].SetVehicle(citizen, vehicleID, 0);
                }
                else
                {
                    manager2.ReleaseCitizen(citizen);
                }
            }
        }
    }

    public override void CreateVehicle(ushort vehicleID, ref Vehicle data)
    {
        base.CreateVehicle(vehicleID, ref data);
        data.m_flags |= Vehicle.Flags.WaitingTarget;
        Singleton<CitizenManager>.instance.CreateUnits(out data.m_citizenUnits, ref Singleton<SimulationManager>.instance.m_randomizer, 0, vehicleID, 0, 0, 0, this.m_firemanCount, 0);
    }

    private bool ExtinguishFire(ushort vehicleID, ref Vehicle data, ushort buildingID, ref Building buildingData)
    {
        int width = buildingData.Width;
        int length = buildingData.Length;
        int num3 = Mathf.Min(0x1388, buildingData.m_fireIntensity * (width * length));
        if ((num3 != 0) && (Singleton<SimulationManager>.instance.m_randomizer.Int32(8) == 0))
        {
            num3 = Mathf.Max(num3 - this.m_fireFightingRate, 0) / (width * length);
            buildingData.m_fireIntensity = (byte)num3;
            if (num3 == 0)
            {
                if (data.m_sourceBuilding != 0)
                {
                    int tempExport = Singleton<BuildingManager>.instance.m_buildings.m_buffer[data.m_sourceBuilding].m_tempExport;
                    Singleton<BuildingManager>.instance.m_buildings.m_buffer[data.m_sourceBuilding].m_tempExport = (byte)Mathf.Min(tempExport + 1, 0xff);
                }
                Building.Flags flags = buildingData.m_flags;
                if (buildingData.m_productionRate != 0)
                {
                    buildingData.m_flags |= Building.Flags.Active;
                }
                Building.Flags flags2 = buildingData.m_flags;
                Singleton<BuildingManager>.instance.UpdateBuildingRenderer(buildingID, buildingData.GetLastFrameData().m_fireDamage == 0);
                if (flags2 != flags)
                {
                    Singleton<BuildingManager>.instance.UpdateFlags(buildingID, flags2 ^ flags);
                }
                if (Singleton<GuideManager>.instance.m_properties != null)
                {
                    Singleton<BuildingManager>.instance.m_buildingOnFire.Deactivate(buildingID, false);
                }
            }
        }
        return (num3 == 0);
    }

    public override void GetBufferStatus(ushort vehicleID, ref Vehicle data, out string localeKey, out int current, out int max)
    {
        localeKey = "Default";
        current = 0;
        max = 0;
    }

    public override Color GetColor(ushort vehicleID, ref Vehicle data, InfoManager.InfoMode infoMode)
    {
        if (infoMode == InfoManager.InfoMode.FireSafety)
        {
            return Singleton<InfoManager>.instance.m_properties.m_modeProperties[(int)infoMode].m_activeColor;
        }
        return base.GetColor(vehicleID, ref data, infoMode);
    }

    public override string GetLocalizedStatus(ushort vehicleID, ref Vehicle data, out InstanceID target)
    {
        if ((data.m_flags & Vehicle.Flags.GoingBack) != Vehicle.Flags.None)
        {
            target = InstanceID.Empty;
            return Locale.Get("VEHICLE_STATUS_FIRETRUCK_RETURN");
        }
        if ((data.m_flags & Vehicle.Flags.WaitingTarget) != Vehicle.Flags.None)
        {
            target = InstanceID.Empty;
            return Locale.Get("VEHICLE_STATUS_FIRETRUCK_WAIT");
        }
        if ((data.m_flags & Vehicle.Flags.Emergency2) != Vehicle.Flags.None)
        {
            if (data.m_targetBuilding != 0)
            {
                target = InstanceID.Empty;
                target.Building = data.m_targetBuilding;
                return Locale.Get("VEHICLE_STATUS_FIRETRUCK_EMERGENCY");
            }
        }
        else if (((data.m_flags & Vehicle.Flags.Emergency1) != Vehicle.Flags.None) && (data.m_targetBuilding != 0))
        {
            target = InstanceID.Empty;
            return Locale.Get("VEHICLE_STATUS_FIRETRUCK_EXTINGUISH");
        }
        target = InstanceID.Empty;
        return Locale.Get("VEHICLE_STATUS_CONFUSED");
    }

    public override void GetSize(ushort vehicleID, ref Vehicle data, out int size, out int max)
    {
        size = 0;
        max = this.m_fireFightingRate;
    }

    public override InstanceID GetTargetID(ushort vehicleID, ref Vehicle vehicleData)
    {
        InstanceID eid = new InstanceID();
        if ((vehicleData.m_flags & Vehicle.Flags.GoingBack) != Vehicle.Flags.None)
        {
            eid.Building = vehicleData.m_sourceBuilding;
            return eid;
        }
        eid.Building = vehicleData.m_targetBuilding;
        return eid;
    }

    protected override bool IgnoreBlocked(ushort vehicleID, ref Vehicle vehicleData)
    {
        return ((vehicleData.m_flags & (Vehicle.Flags.Emergency2 | Vehicle.Flags.Emergency1)) != Vehicle.Flags.None);
    }

    public override void LoadVehicle(ushort vehicleID, ref Vehicle data)
    {
        base.LoadVehicle(vehicleID, ref data);
        if (data.m_sourceBuilding != 0)
        {
            Singleton<BuildingManager>.instance.m_buildings.m_buffer[data.m_sourceBuilding].AddOwnVehicle(vehicleID, ref data);
        }
        if (data.m_targetBuilding != 0)
        {
            Singleton<BuildingManager>.instance.m_buildings.m_buffer[data.m_targetBuilding].AddGuestVehicle(vehicleID, ref data);
        }
    }

    public override void ReleaseVehicle(ushort vehicleID, ref Vehicle data)
    {
        this.RemoveOffers(vehicleID, ref data);
        this.RemoveSource(vehicleID, ref data);
        this.RemoveTarget(vehicleID, ref data);
        base.ReleaseVehicle(vehicleID, ref data);
    }

    private void RemoveOffers(ushort vehicleID, ref Vehicle data)
    {
        if ((data.m_flags & Vehicle.Flags.WaitingTarget) != Vehicle.Flags.None)
        {
            TransferManager.TransferOffer offer = new TransferManager.TransferOffer
            {
                Vehicle = vehicleID
            };
            Singleton<TransferManager>.instance.RemoveIncomingOffer((TransferManager.TransferReason)data.m_transferType, offer);
        }
    }

    private void RemoveSource(ushort vehicleID, ref Vehicle data)
    {
        if (data.m_sourceBuilding != 0)
        {
            Singleton<BuildingManager>.instance.m_buildings.m_buffer[data.m_sourceBuilding].RemoveOwnVehicle(vehicleID, ref data);
            data.m_sourceBuilding = 0;
        }
    }

    private void RemoveTarget(ushort vehicleID, ref Vehicle data)
    {
        if (data.m_targetBuilding != 0)
        {
            Singleton<BuildingManager>.instance.m_buildings.m_buffer[data.m_targetBuilding].RemoveGuestVehicle(vehicleID, ref data);
            data.m_targetBuilding = 0;
        }
    }

    public override void SetSource(ushort vehicleID, ref Vehicle data, ushort sourceBuilding)
    {
        this.RemoveSource(vehicleID, ref data);
        data.m_sourceBuilding = sourceBuilding;
        if (sourceBuilding != 0)
        {
            data.Unspawn(vehicleID);
            data.m_frame0 = new Vehicle.Frame(Singleton<BuildingManager>.instance.m_buildings.m_buffer[sourceBuilding].m_position, Quaternion.identity);
            data.m_frame1 = data.m_frame0;
            data.m_frame2 = data.m_frame0;
            data.m_frame3 = data.m_frame0;
            data.m_targetPos0 = Singleton<BuildingManager>.instance.m_buildings.m_buffer[sourceBuilding].CalculateSidewalkPosition();
            data.m_targetPos0.w = 2f;
            data.m_targetPos1 = data.m_targetPos0;
            data.m_targetPos2 = data.m_targetPos0;
            data.m_targetPos3 = data.m_targetPos0;
            this.FrameDataUpdated(vehicleID, ref data, ref data.m_frame0);
            Singleton<BuildingManager>.instance.m_buildings.m_buffer[sourceBuilding].AddOwnVehicle(vehicleID, ref data);
        }
    }

    public override void SetTarget(ushort vehicleID, ref Vehicle data, ushort targetBuilding)
    {
        this.RemoveTarget(vehicleID, ref data);
        data.m_targetBuilding = targetBuilding;
        data.m_flags &= ~Vehicle.Flags.WaitingTarget;
        data.m_waitCounter = 0;
        if (targetBuilding != 0)
        {
            data.m_flags &= ~Vehicle.Flags.GoingBack;
            data.m_flags |= Vehicle.Flags.Emergency2;
            Singleton<BuildingManager>.instance.m_buildings.m_buffer[targetBuilding].AddGuestVehicle(vehicleID, ref data);
        }
        else
        {
            data.m_flags &= ~(Vehicle.Flags.Emergency2 | Vehicle.Flags.Emergency1);
            if (!this.ShouldReturnToSource(vehicleID, ref data))
            {
                TransferManager.TransferOffer offer = new TransferManager.TransferOffer
                {
                    Priority = 3,
                    Vehicle = vehicleID
                };
                if (data.m_sourceBuilding != 0)
                {
                    offer.Position = (Vector3)((data.GetLastFramePosition() + Singleton<BuildingManager>.instance.m_buildings.m_buffer[data.m_sourceBuilding].m_position) * 0.5f);
                }
                else
                {
                    offer.Position = data.GetLastFramePosition();
                }
                offer.Amount = 1;
                offer.Active = true;
                Singleton<TransferManager>.instance.AddIncomingOffer((TransferManager.TransferReason)data.m_transferType, offer);
                data.m_flags |= Vehicle.Flags.WaitingTarget;
            }
            else
            {
                data.m_flags |= Vehicle.Flags.GoingBack;
            }
        }
        if (!this.StartPathFind(vehicleID, ref data))
        {
            data.Unspawn(vehicleID);
        }
    }

    private bool ShouldReturnToSource(ushort vehicleID, ref Vehicle data)
    {
        if (data.m_sourceBuilding != 0)
        {
            BuildingManager instance = Singleton<BuildingManager>.instance;
            if (((instance.m_buildings.m_buffer[data.m_sourceBuilding].m_flags & Building.Flags.Active) == Building.Flags.None) && (instance.m_buildings.m_buffer[data.m_sourceBuilding].m_fireIntensity == 0))
            {
                return true;
            }
        }
        return false;
    }

    public override void SimulationStep(ushort vehicleID, ref Vehicle data, Vector3 physicsLodRefPos)
    {
        if (((data.m_flags & Vehicle.Flags.WaitingTarget) != Vehicle.Flags.None) && ((data.m_waitCounter = (byte)(data.m_waitCounter + 1)) > 20))
        {
            this.RemoveOffers(vehicleID, ref data);
            data.m_flags &= ~(Vehicle.Flags.WaitingTarget | Vehicle.Flags.Emergency2 | Vehicle.Flags.Emergency1);
            data.m_flags |= Vehicle.Flags.GoingBack;
            data.m_waitCounter = 0;
            if (!this.StartPathFind(vehicleID, ref data))
            {
                data.Unspawn(vehicleID);
            }
        }
        base.SimulationStep(vehicleID, ref data, physicsLodRefPos);
    }

    public override void SimulationStep(ushort vehicleID, ref Vehicle vehicleData, ref Vehicle.Frame frameData, ushort leaderID, ref Vehicle leaderData, int lodPhysics)
    {
        frameData.m_blinkState = ((vehicleData.m_flags & (Vehicle.Flags.Emergency2 | Vehicle.Flags.Emergency1)) == Vehicle.Flags.None) ? 0f : 10f;
        base.SimulationStep(vehicleID, ref vehicleData, ref frameData, leaderID, ref leaderData, lodPhysics);
        bool flag = false;
        if (vehicleData.m_targetBuilding != 0)
        {
            BuildingManager instance = Singleton<BuildingManager>.instance;
            Vector3 vector2 = instance.m_buildings.m_buffer[vehicleData.m_targetBuilding].CalculateSidewalkPosition() - frameData.m_position;
            flag = vector2.sqrMagnitude < 4096f;
            bool flag2 = ((vehicleData.m_flags & Vehicle.Flags.Stopped) != Vehicle.Flags.None) || (frameData.m_velocity.sqrMagnitude < 0.01f);
            if (flag && ((vehicleData.m_flags & Vehicle.Flags.Emergency2) != Vehicle.Flags.None))
            {
                vehicleData.m_flags = (vehicleData.m_flags & ~Vehicle.Flags.Emergency2) | Vehicle.Flags.Emergency1;
            }
            if (flag && flag2)
            {
                if (vehicleData.m_blockCounter > 8)
                {
                    vehicleData.m_blockCounter = 8;
                }
                if ((vehicleData.m_blockCounter == 8) && ((vehicleData.m_flags & Vehicle.Flags.Stopped) == Vehicle.Flags.None))
                {
                    this.ArriveAtTarget(leaderID, ref leaderData);
                }
                if (this.ExtinguishFire(vehicleID, ref vehicleData, vehicleData.m_targetBuilding, ref Singleton<BuildingManager>.instance.m_buildings.m_buffer[vehicleData.m_targetBuilding]))
                {
                    this.SetTarget(vehicleID, ref vehicleData, 0);
                }
            }
            else if (instance.m_buildings.m_buffer[vehicleData.m_targetBuilding].m_fireIntensity == 0)
            {
                this.SetTarget(vehicleID, ref vehicleData, 0);
            }
        }
        if ((((vehicleData.m_flags & Vehicle.Flags.Stopped) != Vehicle.Flags.None) && !flag) && this.CanLeave(vehicleID, ref vehicleData))
        {
            vehicleData.m_flags &= ~Vehicle.Flags.Stopped;
            vehicleData.m_flags |= Vehicle.Flags.Leaving;
        }
        if ((vehicleData.m_flags & Vehicle.Flags.GoingBack) == Vehicle.Flags.None)
        {
            if (this.ShouldReturnToSource(vehicleID, ref vehicleData))
            {
                this.SetTarget(vehicleID, ref vehicleData, 0);
            }
        }
        else if ((((Singleton<SimulationManager>.instance.m_currentFrameIndex >> 4) & 15) == (vehicleID & 15)) && !this.ShouldReturnToSource(vehicleID, ref vehicleData))
        {
            TransferManager.TransferOffer offer = new TransferManager.TransferOffer
            {
                Priority = 3,
                Vehicle = vehicleID,
                Position = frameData.m_position,
                Amount = 1,
                Active = true
            };
            Singleton<TransferManager>.instance.AddIncomingOffer((TransferManager.TransferReason)vehicleData.m_transferType, offer);
        }
    }

    protected override bool StartPathFind(ushort vehicleID, ref Vehicle vehicleData)
    {
        if ((vehicleData.m_flags & Vehicle.Flags.WaitingTarget) != Vehicle.Flags.None)
        {
            return true;
        }
        if ((vehicleData.m_flags & Vehicle.Flags.GoingBack) != Vehicle.Flags.None)
        {
            if (vehicleData.m_sourceBuilding != 0)
            {
                Vector3 endPos = Singleton<BuildingManager>.instance.m_buildings.m_buffer[vehicleData.m_sourceBuilding].CalculateSidewalkPosition();
                return this.StartPathFind(vehicleID, ref vehicleData, (Vector3)vehicleData.m_targetPos3, endPos);
            }
        }
        else if (vehicleData.m_targetBuilding != 0)
        {
            Vector3 vector2 = Singleton<BuildingManager>.instance.m_buildings.m_buffer[vehicleData.m_targetBuilding].CalculateSidewalkPosition();
            return this.StartPathFind(vehicleID, ref vehicleData, (Vector3)vehicleData.m_targetPos3, vector2);
        }
        return false;
    }

    public override void StartTransfer(ushort vehicleID, ref Vehicle data, TransferManager.TransferReason material, TransferManager.TransferOffer offer)
    {
        if (material == ((TransferManager.TransferReason)data.m_transferType))
        {
            if ((data.m_flags & (Vehicle.Flags.WaitingTarget | Vehicle.Flags.GoingBack)) != Vehicle.Flags.None)
            {
                this.SetTarget(vehicleID, ref data, offer.Building);
            }
        }
        else
        {
            base.StartTransfer(vehicleID, ref data, material, offer);
        }
    }

    public override void UpdateBuildingTargetPositions(ushort vehicleID, ref Vehicle vehicleData, Vector3 refPos, ushort leaderID, ref Vehicle leaderData, ref int index, float minSqrDistance)
    {
        if ((leaderData.m_flags & Vehicle.Flags.WaitingTarget) == Vehicle.Flags.None)
        {
            if ((leaderData.m_flags & Vehicle.Flags.GoingBack) != Vehicle.Flags.None)
            {
                if (leaderData.m_sourceBuilding != 0)
                {
                    Vector3 vector;
                    Vector3 vector2;
                    BuildingManager instance = Singleton<BuildingManager>.instance;
                    BuildingInfo info = instance.m_buildings.m_buffer[leaderData.m_sourceBuilding].Info;
                    Randomizer randomizer = new Randomizer((int)vehicleID);
                    info.m_buildingAI.CalculateUnspawnPosition(vehicleData.m_sourceBuilding, ref instance.m_buildings.m_buffer[leaderData.m_sourceBuilding], ref randomizer, base.m_info, out vector, out vector2);
                    vehicleData.SetTargetPos(index++, base.CalculateTargetPoint(refPos, vector2, minSqrDistance, 2f));
                }
            }
            else if (leaderData.m_targetBuilding != 0)
            {
                BuildingManager manager2 = Singleton<BuildingManager>.instance;
                int width = manager2.m_buildings.m_buffer[leaderData.m_targetBuilding].Width;
                int length = manager2.m_buildings.m_buffer[leaderData.m_targetBuilding].Length;
                int num4 = ((Mathf.Min(0x1388, manager2.m_buildings.m_buffer[leaderData.m_targetBuilding].m_fireIntensity * (width * length)) + (this.m_fireFightingRate * 15)) - 1) / (this.m_fireFightingRate * 15);
                Vector3 position = manager2.m_buildings.m_buffer[leaderData.m_targetBuilding].m_position;
                Vector3 rhs = (Vector3)(vehicleData.GetLastFrameData().m_rotation * Vector3.forward);
                position += (Vector3)(rhs * Mathf.Max((float)0f, (float)((num4 - 1) * 3f)));
                Vector3 targetPos = refPos + ((Vector3)(Mathf.Max(0.001f, Vector3.Dot(position - refPos, rhs)) * rhs));
                vehicleData.SetTargetPos(index++, base.CalculateTargetPoint(refPos, targetPos, minSqrDistance, 2f));
            }
        }
    }
}
