// Generated by .NET Reflector from C:\Projects\Skylines\DifficultyMod\DifficultyMod\libs\Assembly-CSharp.dll
using ColossalFramework;
using ColossalFramework.Globalization;
using ColossalFramework.Math;
using System;
using System.Runtime.InteropServices;
using UnityEngine;

public class PoliceCarAIMod : CarAIMod
{
    public int m_crimeCapacity = 0xc350;
    public int m_policeCount = 2;

    public override bool ArriveAtDestination(ushort vehicleID, ref Vehicle vehicleData)
    {
        if ((vehicleData.m_flags & Vehicle.Flags.WaitingTarget) != Vehicle.Flags.None)
        {
            return false;
        }
        if ((vehicleData.m_flags & Vehicle.Flags.GoingBack) != Vehicle.Flags.None)
        {
            return this.ArriveAtSource(vehicleID, ref vehicleData);
        }
        return this.ArriveAtTarget(vehicleID, ref vehicleData);
    }

    private bool ArriveAtSource(ushort vehicleID, ref Vehicle data)
    {
        if (data.m_sourceBuilding == 0)
        {
            Singleton<VehicleManager>.instance.ReleaseVehicle(vehicleID);
            return true;
        }
        int transferSize = data.m_transferSize;
        Singleton<BuildingManager>.instance.m_buildings.m_buffer[data.m_sourceBuilding].Info.m_buildingAI.ModifyMaterialBuffer(data.m_sourceBuilding, ref Singleton<BuildingManager>.instance.m_buildings.m_buffer[data.m_sourceBuilding], (TransferManager.TransferReason)data.m_transferType, ref transferSize);
        data.m_transferSize = (ushort)Mathf.Clamp(data.m_transferSize - transferSize, 0, data.m_transferSize);
        this.RemoveSource(vehicleID, ref data);
        return true;
    }

    private bool ArriveAtTarget(ushort vehicleID, ref Vehicle data)
    {
        if (data.m_targetBuilding == 0)
        {
            return true;
        }
        int amountDelta = 0;
        if ((data.m_flags & Vehicle.Flags.TransferToTarget) != Vehicle.Flags.None)
        {
            amountDelta = data.m_transferSize;
        }
        if ((data.m_flags & Vehicle.Flags.TransferToSource) != Vehicle.Flags.None)
        {
            amountDelta = Mathf.Min(0, data.m_transferSize - this.m_crimeCapacity);
        }
        Singleton<BuildingManager>.instance.m_buildings.m_buffer[data.m_targetBuilding].Info.m_buildingAI.ModifyMaterialBuffer(data.m_targetBuilding, ref Singleton<BuildingManager>.instance.m_buildings.m_buffer[data.m_targetBuilding], (TransferManager.TransferReason)data.m_transferType, ref amountDelta);
        data.m_transferSize = (ushort)(data.m_transferSize + ((ushort)Mathf.Max(0, -amountDelta)));
        if ((data.m_flags & Vehicle.Flags.Emergency2) != Vehicle.Flags.None)
        {
            for (int i = 0; i < this.m_policeCount; i++)
            {
                this.CreatePolice(vehicleID, ref data, Citizen.AgePhase.Adult0);
            }
            data.m_flags |= Vehicle.Flags.Stopped;
        }
        this.SetTarget(vehicleID, ref data, 0);
        return false;
    }

    public override void BuildingRelocated(ushort vehicleID, ref Vehicle data, ushort building)
    {
        base.BuildingRelocated(vehicleID, ref data, building);
        if (building == data.m_sourceBuilding)
        {
            if ((data.m_flags & Vehicle.Flags.GoingBack) != Vehicle.Flags.None)
            {
                this.InvalidPath(vehicleID, ref data, vehicleID, ref data);
            }
        }
        else if ((building == data.m_targetBuilding) && ((data.m_flags & Vehicle.Flags.GoingBack) == Vehicle.Flags.None))
        {
            this.InvalidPath(vehicleID, ref data, vehicleID, ref data);
        }
    }

    protected override float CalculateTargetSpeed(ushort vehicleID, ref Vehicle data, float speedLimit, float curve)
    {
        if ((data.m_flags & Vehicle.Flags.Emergency2) == Vehicle.Flags.None)
        {
            return base.CalculateTargetSpeed(vehicleID, ref data, speedLimit, curve);
        }
        return Mathf.Min(base.CalculateTargetSpeed(vehicleID, ref data, speedLimit * 1.25f, curve * 0.5f), base.m_info.m_maxSpeed);
    }

    public override bool CanLeave(ushort vehicleID, ref Vehicle vehicleData)
    {
        CitizenManager instance = Singleton<CitizenManager>.instance;
        bool flag = true;
        bool flag2 = false;
        uint citizenUnits = vehicleData.m_citizenUnits;
        int num2 = 0;
        while (citizenUnits != 0)
        {
            uint nextUnit = instance.m_units.m_buffer[citizenUnits].m_nextUnit;
            for (int i = 0; i < 5; i++)
            {
                uint citizen = instance.m_units.m_buffer[citizenUnits].GetCitizen(i);
                if (citizen != 0)
                {
                    ushort index = instance.m_citizens.m_buffer[citizen].m_instance;
                    if ((index != 0) && (instance.m_instances.m_buffer[index].Info.m_class.m_service == base.m_info.m_class.m_service))
                    {
                        if (((instance.m_instances.m_buffer[index].m_flags & CitizenInstance.Flags.EnteringVehicle) == CitizenInstance.Flags.None) && ((instance.m_instances.m_buffer[index].m_flags & CitizenInstance.Flags.Character) != CitizenInstance.Flags.None))
                        {
                            flag2 = true;
                        }
                        flag = false;
                    }
                }
            }
            citizenUnits = nextUnit;
            if (++num2 > 0x80000)
            {
                CODebugBase<LogChannel>.Error(LogChannel.Core, "Invalid list detected!\n" + System.Environment.StackTrace);
                break;
            }
        }
        if (!flag2 && !flag)
        {
            citizenUnits = vehicleData.m_citizenUnits;
            num2 = 0;
            while (citizenUnits != 0)
            {
                uint num7 = instance.m_units.m_buffer[citizenUnits].m_nextUnit;
                for (int j = 0; j < 5; j++)
                {
                    uint num9 = instance.m_units.m_buffer[citizenUnits].GetCitizen(j);
                    if (num9 != 0)
                    {
                        ushort num10 = instance.m_citizens.m_buffer[num9].m_instance;
                        if ((num10 != 0) && ((instance.m_instances.m_buffer[num10].m_flags & CitizenInstance.Flags.EnteringVehicle) == CitizenInstance.Flags.None))
                        {
                            instance.m_instances.m_buffer[num10].Info.m_citizenAI.SetTarget(num10, ref instance.m_instances.m_buffer[num10], 0);
                        }
                    }
                }
                citizenUnits = num7;
                if (++num2 > 0x80000)
                {
                    CODebugBase<LogChannel>.Error(LogChannel.Core, "Invalid list detected!\n" + System.Environment.StackTrace);
                    return flag;
                }
            }
        }
        return flag;
    }

    private void CreatePolice(ushort vehicleID, ref Vehicle data, Citizen.AgePhase agePhase)
    {
        SimulationManager instance = Singleton<SimulationManager>.instance;
        CitizenManager manager2 = Singleton<CitizenManager>.instance;
        CitizenInfo info = manager2.GetGroupCitizenInfo(ref instance.m_randomizer, base.m_info.m_class.m_service, Citizen.Gender.Male, agePhase);
        if (info != null)
        {
            int family = instance.m_randomizer.Int32(0x100);
            uint citizen = 0;
            if (manager2.CreateCitizen(out citizen, 90, family, ref instance.m_randomizer, info.m_gender))
            {
                ushort num3;
                if (manager2.CreateCitizenInstance(out num3, ref instance.m_randomizer, info, citizen))
                {
                    Vector3 randomDoorPosition = data.GetRandomDoorPosition(ref instance.m_randomizer, VehicleInfo.DoorType.Exit);
                    info.m_citizenAI.SetCurrentVehicle(num3, ref manager2.m_instances.m_buffer[num3], 0, 0, randomDoorPosition);
                    info.m_citizenAI.SetTarget(num3, ref manager2.m_instances.m_buffer[num3], data.m_targetBuilding);
                    manager2.m_citizens.m_buffer[citizen].SetVehicle(citizen, vehicleID, 0);
                }
                else
                {
                    manager2.ReleaseCitizen(citizen);
                }
            }
        }
    }

    public override void CreateVehicle(ushort vehicleID, ref Vehicle data)
    {
        base.CreateVehicle(vehicleID, ref data);
        data.m_flags |= Vehicle.Flags.WaitingTarget;
        Singleton<CitizenManager>.instance.CreateUnits(out data.m_citizenUnits, ref Singleton<SimulationManager>.instance.m_randomizer, 0, vehicleID, 0, 0, 0, this.m_policeCount, 0);
    }

    public override void GetBufferStatus(ushort vehicleID, ref Vehicle data, out string localeKey, out int current, out int max)
    {
        localeKey = "Police";
        current = data.m_transferSize;
        max = this.m_crimeCapacity;
        if (((data.m_flags & Vehicle.Flags.GoingBack) == Vehicle.Flags.None) && (current == max))
        {
            current = max - 1;
        }
    }

    public override Color GetColor(ushort vehicleID, ref Vehicle data, InfoManager.InfoMode infoMode)
    {
        if (infoMode == InfoManager.InfoMode.CrimeRate)
        {
            return Singleton<InfoManager>.instance.m_properties.m_modeProperties[(int)infoMode].m_activeColor;
        }
        return base.GetColor(vehicleID, ref data, infoMode);
    }

    public override string GetLocalizedStatus(ushort vehicleID, ref Vehicle data, out InstanceID target)
    {
        if ((data.m_flags & Vehicle.Flags.GoingBack) != Vehicle.Flags.None)
        {
            target = InstanceID.Empty;
            return Locale.Get("VEHICLE_STATUS_POLICE_RETURN");
        }
        if ((data.m_flags & Vehicle.Flags.Stopped) != Vehicle.Flags.None)
        {
            target = InstanceID.Empty;
            return Locale.Get("VEHICLE_STATUS_POLICE_STOPPED");
        }
        if ((data.m_flags & Vehicle.Flags.WaitingTarget) != Vehicle.Flags.None)
        {
            if ((data.m_flags & Vehicle.Flags.Leaving) != Vehicle.Flags.None)
            {
                target = InstanceID.Empty;
                return Locale.Get("VEHICLE_STATUS_POLICE_STOP_WAIT");
            }
            target = InstanceID.Empty;
            return Locale.Get("VEHICLE_STATUS_POLICE_PATROL_WAIT");
        }
        if ((data.m_flags & Vehicle.Flags.Emergency2) != Vehicle.Flags.None)
        {
            if (data.m_targetBuilding != 0)
            {
                target = InstanceID.Empty;
                target.Building = data.m_targetBuilding;
                return Locale.Get("VEHICLE_STATUS_POLICE_EMERGENCY");
            }
            target = InstanceID.Empty;
            return Locale.Get("VEHICLE_STATUS_CONFUSED");
        }
        target = InstanceID.Empty;
        return Locale.Get("VEHICLE_STATUS_POLICE_PATROL");
    }

    public override void GetSize(ushort vehicleID, ref Vehicle data, out int size, out int max)
    {
        size = data.m_transferSize;
        max = this.m_crimeCapacity;
    }

    public override InstanceID GetTargetID(ushort vehicleID, ref Vehicle vehicleData)
    {
        InstanceID eid = new InstanceID();
        if ((vehicleData.m_flags & Vehicle.Flags.GoingBack) != Vehicle.Flags.None)
        {
            eid.Building = vehicleData.m_sourceBuilding;
            return eid;
        }
        eid.Building = vehicleData.m_targetBuilding;
        return eid;
    }

    public override void LoadVehicle(ushort vehicleID, ref Vehicle data)
    {
        base.LoadVehicle(vehicleID, ref data);
        if (data.m_sourceBuilding != 0)
        {
            Singleton<BuildingManager>.instance.m_buildings.m_buffer[data.m_sourceBuilding].AddOwnVehicle(vehicleID, ref data);
        }
        if (data.m_targetBuilding != 0)
        {
            Singleton<BuildingManager>.instance.m_buildings.m_buffer[data.m_targetBuilding].AddGuestVehicle(vehicleID, ref data);
        }
    }

    public override void ReleaseVehicle(ushort vehicleID, ref Vehicle data)
    {
        this.RemoveOffers(vehicleID, ref data);
        this.RemoveSource(vehicleID, ref data);
        this.RemoveTarget(vehicleID, ref data);
        base.ReleaseVehicle(vehicleID, ref data);
    }

    private void RemoveOffers(ushort vehicleID, ref Vehicle data)
    {
        if ((data.m_flags & Vehicle.Flags.WaitingTarget) != Vehicle.Flags.None)
        {
            TransferManager.TransferOffer offer = new TransferManager.TransferOffer
            {
                Vehicle = vehicleID
            };
            Singleton<TransferManager>.instance.RemoveIncomingOffer((TransferManager.TransferReason)data.m_transferType, offer);
        }
    }

    private void RemoveSource(ushort vehicleID, ref Vehicle data)
    {
        if (data.m_sourceBuilding != 0)
        {
            Singleton<BuildingManager>.instance.m_buildings.m_buffer[data.m_sourceBuilding].RemoveOwnVehicle(vehicleID, ref data);
            data.m_sourceBuilding = 0;
        }
    }

    private void RemoveTarget(ushort vehicleID, ref Vehicle data)
    {
        if (data.m_targetBuilding != 0)
        {
            Singleton<BuildingManager>.instance.m_buildings.m_buffer[data.m_targetBuilding].RemoveGuestVehicle(vehicleID, ref data);
            data.m_targetBuilding = 0;
        }
    }

    public override void SetSource(ushort vehicleID, ref Vehicle data, ushort sourceBuilding)
    {
        this.RemoveSource(vehicleID, ref data);
        data.m_sourceBuilding = sourceBuilding;
        if (sourceBuilding != 0)
        {
            Vector3 vector;
            Vector3 vector2;
            BuildingManager instance = Singleton<BuildingManager>.instance;
            BuildingInfo info = instance.m_buildings.m_buffer[sourceBuilding].Info;
            data.Unspawn(vehicleID);
            Randomizer randomizer = new Randomizer((int)vehicleID);
            info.m_buildingAI.CalculateSpawnPosition(sourceBuilding, ref instance.m_buildings.m_buffer[sourceBuilding], ref randomizer, base.m_info, out vector, out vector2);
            Quaternion identity = Quaternion.identity;
            Vector3 forward = vector2 - vector;
            if (forward.sqrMagnitude > 0.01f)
            {
                identity = Quaternion.LookRotation(forward);
            }
            data.m_frame0 = new Vehicle.Frame(vector, identity);
            data.m_frame1 = data.m_frame0;
            data.m_frame2 = data.m_frame0;
            data.m_frame3 = data.m_frame0;
            data.m_targetPos0 = vector;
            data.m_targetPos0.w = 2f;
            data.m_targetPos1 = vector2;
            data.m_targetPos1.w = 2f;
            data.m_targetPos2 = data.m_targetPos1;
            data.m_targetPos3 = data.m_targetPos1;
            this.FrameDataUpdated(vehicleID, ref data, ref data.m_frame0);
            Singleton<BuildingManager>.instance.m_buildings.m_buffer[sourceBuilding].AddOwnVehicle(vehicleID, ref data);
        }
    }

    public override void SetTarget(ushort vehicleID, ref Vehicle data, ushort targetBuilding)
    {
        this.RemoveTarget(vehicleID, ref data);
        data.m_targetBuilding = targetBuilding;
        data.m_flags &= ~Vehicle.Flags.WaitingTarget;
        data.m_waitCounter = 0;
        if (targetBuilding != 0)
        {
            if (Singleton<SimulationManager>.instance.m_randomizer.Int32(10) == 0)
            {
                data.m_flags |= Vehicle.Flags.Emergency2;
            }
            else
            {
                data.m_flags &= ~Vehicle.Flags.Emergency2;
            }
            Singleton<BuildingManager>.instance.m_buildings.m_buffer[targetBuilding].AddGuestVehicle(vehicleID, ref data);
        }
        else
        {
            data.m_flags &= ~Vehicle.Flags.Emergency2;
            if ((data.m_transferSize < this.m_crimeCapacity) && !this.ShouldReturnToSource(vehicleID, ref data))
            {
                TransferManager.TransferOffer offer = new TransferManager.TransferOffer
                {
                    Priority = 7,
                    Vehicle = vehicleID
                };
                if (data.m_sourceBuilding != 0)
                {
                    offer.Position = (Vector3)((data.GetLastFramePosition() + Singleton<BuildingManager>.instance.m_buildings.m_buffer[data.m_sourceBuilding].m_position) * 0.5f);
                }
                else
                {
                    offer.Position = data.GetLastFramePosition();
                }
                offer.Amount = 1;
                offer.Active = true;
                Singleton<TransferManager>.instance.AddIncomingOffer((TransferManager.TransferReason)data.m_transferType, offer);
                data.m_flags |= Vehicle.Flags.WaitingTarget;
            }
            else
            {
                data.m_flags |= Vehicle.Flags.GoingBack;
            }
        }
        if (!this.StartPathFind(vehicleID, ref data))
        {
            data.Unspawn(vehicleID);
        }
    }

    private bool ShouldReturnToSource(ushort vehicleID, ref Vehicle data)
    {
        if (data.m_sourceBuilding != 0)
        {
            BuildingManager instance = Singleton<BuildingManager>.instance;
            if (((instance.m_buildings.m_buffer[data.m_sourceBuilding].m_flags & Building.Flags.Active) == Building.Flags.None) && (instance.m_buildings.m_buffer[data.m_sourceBuilding].m_fireIntensity == 0))
            {
                return true;
            }
        }
        return false;
    }

    public override void SimulationStep(ushort vehicleID, ref Vehicle data, Vector3 physicsLodRefPos)
    {
        if (((data.m_flags & Vehicle.Flags.WaitingTarget) != Vehicle.Flags.None) && ((data.m_waitCounter = (byte)(data.m_waitCounter + 1)) > 20))
        {
            this.RemoveOffers(vehicleID, ref data);
            data.m_flags &= ~(Vehicle.Flags.WaitingTarget | Vehicle.Flags.Emergency2);
            data.m_flags |= Vehicle.Flags.GoingBack;
            data.m_waitCounter = 0;
            if (!this.StartPathFind(vehicleID, ref data))
            {
                data.Unspawn(vehicleID);
            }
        }
        base.SimulationStep(vehicleID, ref data, physicsLodRefPos);
    }

    public override void SimulationStep(ushort vehicleID, ref Vehicle vehicleData, ref Vehicle.Frame frameData, ushort leaderID, ref Vehicle leaderData, int lodPhysics)
    {
        frameData.m_blinkState = ((vehicleData.m_flags & Vehicle.Flags.Emergency2) == Vehicle.Flags.None) ? 0f : 10f;
        this.TryCollectCrime(vehicleID, ref vehicleData, ref frameData);
        base.SimulationStep(vehicleID, ref vehicleData, ref frameData, leaderID, ref leaderData, lodPhysics);
        if ((vehicleData.m_flags & Vehicle.Flags.Stopped) != Vehicle.Flags.None)
        {
            if (this.CanLeave(vehicleID, ref vehicleData))
            {
                vehicleData.m_flags &= ~Vehicle.Flags.Stopped;
                vehicleData.m_flags |= Vehicle.Flags.Leaving;
            }
        }
        else if ((((vehicleData.m_flags & Vehicle.Flags.Arriving) != Vehicle.Flags.None) && (vehicleData.m_targetBuilding != 0)) && ((vehicleData.m_flags & (Vehicle.Flags.WaitingTarget | Vehicle.Flags.GoingBack | Vehicle.Flags.WaitingPath | Vehicle.Flags.Emergency2)) == Vehicle.Flags.None))
        {
            this.ArriveAtTarget(vehicleID, ref vehicleData);
        }
        if (((vehicleData.m_flags & Vehicle.Flags.GoingBack) == Vehicle.Flags.None) && this.ShouldReturnToSource(vehicleID, ref vehicleData))
        {
            this.SetTarget(vehicleID, ref vehicleData, 0);
        }
    }

    protected override bool StartPathFind(ushort vehicleID, ref Vehicle vehicleData)
    {
        if ((vehicleData.m_flags & Vehicle.Flags.WaitingTarget) != Vehicle.Flags.None)
        {
            return true;
        }
        if ((vehicleData.m_flags & Vehicle.Flags.GoingBack) != Vehicle.Flags.None)
        {
            if (vehicleData.m_sourceBuilding != 0)
            {
                Vector3 endPos = Singleton<BuildingManager>.instance.m_buildings.m_buffer[vehicleData.m_sourceBuilding].CalculateSidewalkPosition();
                return this.StartPathFind(vehicleID, ref vehicleData, (Vector3)vehicleData.m_targetPos3, endPos);
            }
        }
        else if (vehicleData.m_targetBuilding != 0)
        {
            Vector3 vector2 = Singleton<BuildingManager>.instance.m_buildings.m_buffer[vehicleData.m_targetBuilding].CalculateSidewalkPosition();
            return this.StartPathFind(vehicleID, ref vehicleData, (Vector3)vehicleData.m_targetPos3, vector2);
        }
        return false;
    }

    public override void StartTransfer(ushort vehicleID, ref Vehicle data, TransferManager.TransferReason material, TransferManager.TransferOffer offer)
    {
        if (material == ((TransferManager.TransferReason)data.m_transferType))
        {
            if ((data.m_flags & Vehicle.Flags.WaitingTarget) != Vehicle.Flags.None)
            {
                this.SetTarget(vehicleID, ref data, offer.Building);
            }
        }
        else
        {
            base.StartTransfer(vehicleID, ref data, material, offer);
        }
    }

    private void TryCollectCrime(ushort vehicleID, ref Vehicle vehicleData, ref Vehicle.Frame frameData)
    {
        Vector3 position = frameData.m_position;
        float num = position.x - 32f;
        float num2 = position.z - 32f;
        float num3 = position.x + 32f;
        float num4 = position.z + 32f;
        int num5 = Mathf.Max((int)(((num - 72f) / 64f) + 135f), 0);
        int num6 = Mathf.Max((int)(((num2 - 72f) / 64f) + 135f), 0);
        int num7 = Mathf.Min((int)(((num3 + 72f) / 64f) + 135f), 0x10d);
        int num8 = Mathf.Min((int)(((num4 + 72f) / 64f) + 135f), 0x10d);
        BuildingManager instance = Singleton<BuildingManager>.instance;
        for (int i = num6; i <= num8; i++)
        {
            for (int j = num5; j <= num7; j++)
            {
                ushort buildingID = instance.m_buildingGrid[(i * 270) + j];
                int num12 = 0;
                while (buildingID != 0)
                {
                    this.TryCollectCrime(vehicleID, ref vehicleData, ref frameData, buildingID, ref instance.m_buildings.m_buffer[buildingID]);
                    buildingID = instance.m_buildings.m_buffer[buildingID].m_nextGridBuilding;
                    if (++num12 >= 0x8000)
                    {
                        CODebugBase<LogChannel>.Error(LogChannel.Core, "Invalid list detected!\n" + System.Environment.StackTrace);
                        break;
                    }
                }
            }
        }
    }

    private void TryCollectCrime(ushort vehicleID, ref Vehicle vehicleData, ref Vehicle.Frame frameData, ushort buildingID, ref Building building)
    {
        if (Vector3.SqrMagnitude(building.CalculateSidewalkPosition() - frameData.m_position) < 1024f)
        {
            int amountDelta = -this.m_crimeCapacity;
            building.Info.m_buildingAI.ModifyMaterialBuffer(buildingID, ref building, TransferManager.TransferReason.Crime, ref amountDelta);
            if (amountDelta != 0)
            {
                amountDelta = Mathf.Clamp(amountDelta, vehicleData.m_transferSize - this.m_crimeCapacity, 0);
                vehicleData.m_transferSize = (ushort)(vehicleData.m_transferSize + ((ushort)Mathf.Max(0, -amountDelta)));
            }
        }
    }

    public override void UpdateBuildingTargetPositions(ushort vehicleID, ref Vehicle vehicleData, Vector3 refPos, ushort leaderID, ref Vehicle leaderData, ref int index, float minSqrDistance)
    {
        if ((leaderData.m_flags & Vehicle.Flags.WaitingTarget) == Vehicle.Flags.None)
        {
            if ((leaderData.m_flags & Vehicle.Flags.GoingBack) != Vehicle.Flags.None)
            {
                if (leaderData.m_sourceBuilding != 0)
                {
                    Vector3 vector;
                    Vector3 vector2;
                    BuildingManager instance = Singleton<BuildingManager>.instance;
                    BuildingInfo info = instance.m_buildings.m_buffer[leaderData.m_sourceBuilding].Info;
                    Randomizer randomizer = new Randomizer((int)vehicleID);
                    info.m_buildingAI.CalculateUnspawnPosition(vehicleData.m_sourceBuilding, ref instance.m_buildings.m_buffer[leaderData.m_sourceBuilding], ref randomizer, base.m_info, out vector, out vector2);
                    vehicleData.SetTargetPos(index++, base.CalculateTargetPoint(refPos, vector2, minSqrDistance, 2f));
                }
            }
            else if (((leaderData.m_flags & Vehicle.Flags.Emergency2) != Vehicle.Flags.None) && (leaderData.m_targetBuilding != 0))
            {
                Vector3 vector3;
                Vector3 vector4;
                BuildingManager manager2 = Singleton<BuildingManager>.instance;
                BuildingInfo info2 = manager2.m_buildings.m_buffer[leaderData.m_targetBuilding].Info;
                Randomizer randomizer2 = new Randomizer((int)vehicleID);
                info2.m_buildingAI.CalculateUnspawnPosition(vehicleData.m_targetBuilding, ref manager2.m_buildings.m_buffer[leaderData.m_targetBuilding], ref randomizer2, base.m_info, out vector3, out vector4);
                vehicleData.SetTargetPos(index++, base.CalculateTargetPoint(refPos, vector4, minSqrDistance, 2f));
            }
        }
    }
}
